spring:
  data:
    mongodb:
      uri: mongodb+srv://ayushkumar2637_db_user:YGtJ4SvVVzpvcxGH@cluster0.uzfopkq.mongodb.net/?appName=Cluster0
      database: JournalDB
      auto-index-creation: true

server:
  servlet:
    context-path: /journalapplicationdev/v1
  port: 7776