spring.application.name=journalApp
#server.port = 8080
management.endpoints.web.exposure.include=*
#management.endpoint.info.enabled=false

#spring.data.mongodb.uri=mongodb://localhost:27017/JournalDB
spring.data.mongodb.uri=mongodb+srv://ayushkumar2637_db_user:YGtJ4SvVVzpvcxGH@cluster0.uzfopkq.mongodb.net/?appName=Cluster0
spring.data.mongodb.database=JournalDB
#spring.data.mongodb.username=myuser
#spring.data.mongodb.password=mypass
spring.data.mongodb.auto-index-creation=true

#spring.security.user.name=User1
#spring.security.user.password=pass

server.servlet.context-path=/journalapp/v1



#NOTE : 1ST PREFERENCE IS ALWAYS GIVE TO COMMANDLINE ARGUMENT EG : java -jar jarfilename.jar --server.port=7778